### ISSUE TITLE
Go modules support

### ISSUE THREAD

**Issue by AMekss** [dgrr/http2#17]
I noticed that this project is not using [go modules](https://blog.golang.org/using-go-modules) for dependency management. Any objections regarding it? If not I can create a PR to enable it

**Comment by dgrr** [comment]
I don't like it because it doesn't support private repos. Besides that, I'd like to have it because everyone likes it (and use it).

**Comment by AMekss** [comment]
Well the support for private packages could be better, however it is possible - go modules uses `go get` to get the packages which in turn use `git`. So it has no problems locally to fetch whatever your git is authorized to fetch. It's a bit more tricky on CI. In my current company we're using custom docker image with ssh private key for "bot" user which is invited into our GH organisation with read access for private packages - not ideal but gets the job done.

What I like about OpenSource - none of it is a concern! :D
