### ISSUE TITLE
Does not work using net.Listener with TLS

### ISSUE THREAD

**Issue by gitfury** [dgrr/http2#24]
It seems as if using `fasthttp2.ConfigureServer(server)` does not work, even when the server is serving on a TLS listener. Am I doing something incorrect or is there no support for this?

```
	listener, err := net.Listen("tcp4", "0.0.0.0:443")
	if err != nil {
		panic(err)
	}

	tlsListener := tls.NewListener(listener, tlsConfig)

	server := &fasthttp.Server {
		Handler: ServeHTTP,
	}

	fasthttp2.ConfigureServer(server)

	go server.Serve(tlsListener)
```

**Comment by dgrr** [comment]
Oh yes! So you doing something wrong, and I am doing it too!
`ConfigureServer` actually configures the TLSConfig of fasthttp.Server. In that sense, if you are going to use your own `tls.Config` then http2 is not going to work. I'll write a fix for that.

**Comment by dgrr** [comment]
@gitfury You can use `ConfigureServerAndConfig(fasthttpServer, tlsConfig)`

**Comment by gitfury** [comment]
Hi,
Thank you for the response! Maybe I am still doing something wrong, but I am using AutoCert to manage certificates for me dynamically, as such, I cannot set a "start" certificate like in server.ListenAndServeTLS so I used the net.Listener. It looks something like this:

	autoCert := &autocert.Manager{
		Prompt: autocert.AcceptTOS,
		Cache:  autocert.DirCache("/var/delta/certs/"),
	}

```
	tlsConfig := &tls.Config{
		GetCertificate:           autoCert.GetCertificate,
		PreferServerCipherSuites: true,
		CurvePreferences: []tls.CurveID{
			tls.CurveP256,
			tls.X25519, // Go 1.8 only
		},
	}
```
I tried the same code, and used ConfigureServerAndConfig but it still does not work.

**Comment by erikdubbelboer** [comment]
`fasthttp2.ConfigureServerAndConfig(server, tlsConfig)` needs to be called before `tls.NewListener(listener, tlsConfig)` as it makes changes to the `tlsConfig` that `tls.NewListener` needs.

**Comment by gitfury** [comment]
Works, thank you!

**Comment by dgrr** [comment]
You can already do it by yourself, notice that `fasthttp2` is like a third-party package to `http2`. You can already use your own handler like [here](https://github.com/dgrr/http2/blob/v0.0.3/fasthttp2/server.go#L22). For example:
```go
func ConfigureOwnServer(s *fasthttp.Server) *http2.Server {
	s2 := &http2.Server{
		Adaptor: fasthttp2.NewServerAdaptor(s),
	}

	s.NextProto(http2.H2TLSProto, func(c net.Conn) error {
          if c.RemoteAddr().String() != "127.0.0.1:8443" {
            c.Close()
            return errors.New("Not allowed")
          }
          return s2.ServeConn(c)
        })

	return s2
}
```

**Comment by gitfury** [comment]
Ah I see thank you! One more thing, on IOS Safari fasthttp2 does not seem to work, output doesn't seem to say anything but Safari cay "cannot parse response". Is this something you can replicate on your own end or am I doing something wrong again?

**Comment by dgrr** [comment]
Weird. I am able to access http2.gofiber.io from Safari on an iPhone. I'd say is something on your end? Can you enter http2.gofiber.io from there or it happens only on your own website?

**Comment by gitfury** [comment]
I am unable to access that website as well on my iPhone, Safari just says Cannot connect to the server instead of the other error I had with mine.

**Comment by gitfury** [comment]
Ah it works, it was something on my end, I was connecting via http instead of https. Also, is there a way to handle new connections before they get parsed by fasthttp? I see the ConnState hook is what I'm looking for, but I also need to be able to close those connections and I cannot close the connection inside ConnState without getting a panic for "use of closed network connection". Or maybe there's a way I can use my TCP listener to accept the connection, then send it to fasthttp to handle it after?

**Comment by dgrr** [comment]
You can try to make your own net.Listener that wraps the original net.Listener. But, why do you want that? Can I know about your use case?

**Comment by gitfury** [comment]
To gather data about an IP making a connection and to be able to block or accept them before my server spends CPU time parsing their request, etc.

**Comment by dgrr** [comment]
Then you can use the example I gave you before in [this comment](https://github.com/dgrr/http2/issues/24#issuecomment-877825868).

NextProto gets called after the TLS handshake, so fasthttp nor fasthttp2 will spend any time parsing any request on the NextProto callback.

**Comment by gitfury** [comment]
Yes, this works for http2. But I also want it to work for HTTP/1.1.
