### ISSUE TITLE
how do you have any domain names and not pre-specify the domain name?

### ISSUE THREAD

**Issue by hiqsociety** [dgrr/http2#30]
i would like it to be automatically detect incoming hostname so I dont have to WhiteList it. 
any domains at all. how do i do that with this?

https://github.com/dgrr/http2/blob/master/examples/autocert/main.go

i know i can comment out the whitelist host but i dunno how to make it pre-detect/pre-specify the incoming ctx.Request.Host()

**Comment by dgrr** [comment]
Hello. I have no idea. You should do that by using the `Host` header. But I think that's not something specific to http2.
