### ISSUE TITLE
Do you support h2c?

### ISSUE THREAD

**Issue by ts-kst** [dgrr/http2#43]

**Comment by dgrr** [comment]
So far we do not support HTTP/2 over clear text. I know nginx does. But it is not very common.

**Comment by mrkmrtns** [comment]
Is there any plan? With standard library it works and support is there.

I would say in world of microservices it's very common. TLS is done at different level.
Also it's very common to put http2 server behind some reverse proxy what makes TLS for You. Either in those cases connection to service is made via h2c.

**Comment by dgrr** [comment]
No, I have no plans of supporting it. But I do accept PRs
