### ISSUE TITLE
broken integration with fasthttp

### ISSUE THREAD

**Issue by pablolagos** [dgrr/http2#67]
Recent changes in fashttp broke the integration with http2

See: https://github.com/valyala/fasthttp/pull/1602/files

package main

```go
import (
	"github.com/valyala/fasthttp"
	"github.com/dgrr/http2"
)

func main() {
    s := &fasthttp.Server{
        Handler: yourHandler,
        Name:    "HTTP2 test",
    }

    http2.ConfigureServer(s, http2.ServerConfig{})
    
    s.ListenAndServeTLS(...)
}
```

Results in:

`/go/pkg/mod/github.com/dgrr/http2@v0.3.5/configure.go:70:16: cannot use cl.Do (value of type func(req *fasthttp.Request, res *fasthttp.Response) (err error)) as fasthttp.RoundTripper value in assignment: func(req *fasthttp.Request, res *fasthttp.Response) (err error) does not implement fasthttp.RoundTripper (missing method RoundTrip)`

**Comment by dgrr** [comment]
It is sad. I accept PRs if you are willing to contribute. Thanks

**Comment by pablolagos** [comment]
I will!

**Comment by Northernside** [comment]
Any news on this? 😔

**Comment by jney** [comment]
@dgrr it would be great having a release including a7159541b631aa6b5f83e9a930556e98f2dee449

**Comment by dgrr** [comment]
@jney sure

**Comment by Northernside** [comment]
❤️
